# Generated by Django 6.1.1 on 2026-09-03 12:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تلفن')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='نام نمایشی')),
                ('birth_date_gregorian', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد میلادی')),
                ('birth_date_jalali', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد شمسی')),
                ('grade', models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], max_length=2, null=True, verbose_name='پایه تحصیلی')),
                ('field', models.CharField(blank=True, choices=[('experimental', 'تجربی'), ('mathematics', 'ریاضی'), ('humanities', 'انسانی')], max_length=20, null=True, verbose_name='رشته تحصیلی')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='استان')),
                ('school', models.CharField(blank=True, max_length=150, verbose_name='مدرسه')),
                ('theme', models.CharField(choices=[('light', 'روشن'), ('dark', 'تیره'), ('system', 'سیستمی')], default='system', max_length=10, verbose_name='تم')),
                ('primary_color', models.CharField(default='#7055e8', max_length=7, verbose_name='رنگ اصلی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
