# Generated by Django 6.1.1 on 2026-09-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roommembership_unique_active_room_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('focused', 'متمرکز'), ('distracted', 'حواس پرت'), ('away', 'غایب')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='rooms.studysession')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
