# Generated by Django 6.1.1 on 2026-09-08 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_studytimelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='پیام')),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='شناسه کلاینت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='rooms.studyroom', verbose_name='سالن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام چت سالن',
                'verbose_name_plural': 'پیام\u200cهای چت سالن',
                'ordering': ['created_at'],
            },
        ),
    ]
