# Generated by Django 6.1.1 on 2026-09-13 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف'),
        ),
        migrations.AddField(
            model_name='roomchatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_room_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط'),
        ),
        migrations.AddField(
            model_name='roomchatmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف شده'),
        ),
    ]
