# Generated by Django 6.1.1 on 2026-09-13 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomchatmessage_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین ویرایش'),
        ),
        migrations.AddField(
            model_name='roomchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='rooms.roomchatmessage', verbose_name='پاسخ به پیام'),
        ),
        migrations.CreateModel(
            name='RoomChatMessageEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_message', models.TextField(max_length=1000, verbose_name='متن قبل از ویرایش')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ویرایش')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_chat_message_edits', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش شده توسط')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='rooms.roomchatmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'سابقه ویرایش پیام',
                'verbose_name_plural': 'سوابق ویرایش پیام\u200cها',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('cry', 'گریه'), ('laugh', 'خنده'), ('heart', 'قلب'), ('like', 'لایک'), ('dislike', 'دیسلایک')], max_length=20, verbose_name='واکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان واکنش')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rooms.roomchatmessage', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_chat_reactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'واکنش پیام',
                'verbose_name_plural': 'واکنش\u200cهای پیام',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_chat_message_user_reaction')],
            },
        ),
    ]
