# Generated by Django 6.1.1 on 2026-09-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomchatmessage_edited_at_roomchatmessage_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
