# Generated by Django 6.1.1 on 2026-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomchatmessage_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchatmessage',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت مدیریت'),
        ),
    ]
