# Generated by Django 6.1.1 on 2026-09-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_roomchatmessage_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchatmessage',
            name='is_staff',
        ),
    ]
