# Generated by Django 6.1.1 on 2026-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_remove_roomchatmessage_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchatreaction',
            name='reaction',
            field=models.CharField(choices=[('cry', 'گریه'), ('laugh', 'خنده'), ('heart', 'قلب'), ('like', 'لایک'), ('dislike', 'دیسلایک'), ('fire', 'آتش'), ('brain', 'مغز'), ('target', 'هدف'), ('wow', 'واو')], max_length=20, verbose_name='واکنش'),
        ),
    ]
