# Generated by Django 6.1.1 on 2026-09-14 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('maz', 'ماز'), ('kanoon', 'قلمچی'), ('kheilisabz', 'خیلی سبز'), ('dopamine', 'دوپامین'), ('other', 'سایر')], default='dopamine', max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('questions_pdf', models.FileField(blank=True, null=True, upload_to='exams/questions/')),
                ('answer_pdf', models.FileField(blank=True, null=True, upload_to='exams/answers/')),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['start_at', 'end_at', 'is_active'], name='exams_exam_start_a_e90d25_idx'), models.Index(fields=['category'], name='exams_exam_categor_5f3c53_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'در حال آزمون'), ('submitted', 'ثبت شده'), ('expired', 'منقضی شده')], default='in_progress', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='exams_exama_user_id_120f19_idx'), models.Index(fields=['exam', 'status'], name='exams_exama_exam_id_39972c_idx'), models.Index(fields=['expires_at'], name='exams_exama_expires_74f8da_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'exam'), name='unique_exam_attempt_per_user')],
            },
        ),
    ]
