# Generated by Django 6.1.1 on 2026-09-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('start_question', models.PositiveIntegerField(default=1)),
                ('question_count', models.PositiveIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='exams.exam')),
            ],
            options={
                'ordering': ['order', 'start_question'],
                'indexes': [models.Index(fields=['exam', 'order'], name='exams_examb_exam_id_8f480e_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'order'), name='unique_exam_booklet_order')],
            },
        ),
    ]
