# Generated by Django 6.1.1 on 2026-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exambooklet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exambooklet',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='exambooklet',
            name='exams_examb_exam_id_8f480e_idx',
        ),
        migrations.AlterField(
            model_name='exambooklet',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exambooklet',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
