# Generated by Django 6.1.1 on 2026-09-15 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exambooklet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('national_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('national_participants', models.PositiveIntegerField(default=0)),
                ('provincial_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('provincial_participants', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exams.examattempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamBookletResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('decile', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('national_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('national_participants', models.PositiveIntegerField(default=0)),
                ('provincial_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('provincial_participants', models.PositiveIntegerField(default=0)),
                ('national_average', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('provincial_average', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('performance_title', models.CharField(blank=True, default='', max_length=100)),
                ('performance_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exambooklet')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_results', to='exams.examresult')),
            ],
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'is_final'], name='exams_examr_exam_id_77c37a_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['user', 'exam'], name='exams_examr_user_id_3d88d1_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'national_rank'], name='exams_examr_exam_id_6c7320_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'provincial_rank'], name='exams_examr_exam_id_bba11a_idx'),
        ),
        migrations.AddIndex(
            model_name='exambookletresult',
            index=models.Index(fields=['booklet', 'score'], name='exams_examb_booklet_0b7629_idx'),
        ),
        migrations.AddIndex(
            model_name='exambookletresult',
            index=models.Index(fields=['booklet', 'national_rank'], name='exams_examb_booklet_1afaae_idx'),
        ),
        migrations.AddIndex(
            model_name='exambookletresult',
            index=models.Index(fields=['booklet', 'provincial_rank'], name='exams_examb_booklet_ec3d71_idx'),
        ),
        migrations.AddConstraint(
            model_name='exambookletresult',
            constraint=models.UniqueConstraint(fields=('result', 'booklet'), name='unique_result_booklet'),
        ),
    ]
