# Generated by Django 6.1.1 on 2026-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examresult_exambookletresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='raw_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='exambookletresult',
            name='raw_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='examresult',
            name='raw_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='exambookletresult',
            name='national_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='exambookletresult',
            name='provincial_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='exambookletresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
