# Generated by Django 6.1.1 on 2026-09-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examattempt_raw_score_exambookletresult_raw_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer_pdf_url',
            field=models.URLField(blank=True, default='', help_text='اگر لینک خارجی وارد شود، لینک خارجی نسبت به فایل آپلودی اولویت دارد.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_pdf_url',
            field=models.URLField(blank=True, default='', help_text='اگر لینک خارجی وارد شود، لینک خارجی نسبت به فایل آپلودی اولویت دارد.'),
        ),
    ]
