# Generated by Django 6.1.1 on 2026-09-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_answer_pdf_url_exam_questions_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exambooklet',
            name='factor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
