# Generated by Django 6.1.1 on 2026-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exambooklet_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='field',
            field=models.CharField(blank=True, choices=[('experimental', 'تجربی'), ('mathematics', 'ریاضی'), ('humanities', 'انسانی')], max_length=20, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], max_length=2, null=True, verbose_name='پایه تحصیلی'),
        ),
    ]
